In [1]:
from sympy import *
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import *

from scipy.optimize import *
import math

# Relative Maximum

#### Question 1 

The total revenue​ (in hundreds of​ dollars) from the sale of x spas and y solar heaters is approximated by
<br>R(x,y)=18 + 276x + 198y - 7x^2 - 4y^2 - 5xy
<br>Find the number of each that should be sold to produce maximum revenue. Find the maximum revenue.

In [2]:
x = Symbol('x')
y = Symbol('y')

In [3]:
r = -x**2 - y**2 +2*x + 8*y
R = lambdify([x,y],r,'numpy')
print('R(x,y):', r)

R(x,y): -x**2 + 2*x - y**2 + 8*y


In [4]:
rx = diff(r, x)
print('Rx:',rx)
rxx = diff(rx, x)
Rxx = lambdify([x,y],rxx,'numpy')
print('Rxx:',rxx)

ry = diff(r, y)
print('\nRy:',ry)
ryy = diff(ry, y)
Ryy = lambdify([x,y],ryy,'numpy')
print('Ryy:',ryy)

rxy = diff(rx, y)
Rxy = lambdify([x,y],rxy,'numpy')
print('\nRxy:',rxy)


Rx: 2 - 2*x
Rxx: -2

Ry: 8 - 2*y
Ryy: -2

Rxy: 0


In [35]:
# make first derivates = 6 and create matrix to be solved with linear algebra 
coefficients = np.matrix([[14, 5],
                          [5, 8]])
constants    = np.array([276, 198])
intersection = np.linalg.solve(coefficients,constants)
intersection

array([14., 16.])

In [36]:
# Second derivative test
rxx*ryy-rxy**2

87

In [39]:
# Total Revue from 14 units x and 16 units y
R(14,16)*100

353400

# Cobb Douglass Function

The​ Cobb-Douglas production function for a particular product is 
<br>N(x,y) = 80x^0.6 * y^0.4
<br>here x is the number of units of labor and y is the number of units of capital required to produce N(x, y) units of the product. Each unit of labor costs 60 dollars and each unit of capital costs 100 dollars.

In [40]:
x = Symbol('x')
y = Symbol('y')
L = Symbol('L')

In [44]:
# Lagrangian Function
fl = 80*(x**.6)*(y**.4) - L*60*x - L*100*y + L*500000

In [46]:
# First Partial Derivatives of Lagrangian Function
fx = diff(fl, x)
print('fx:',fx)

fy = diff(fl, y)
print('fy:',fy)

fL = diff(fl, L)
print('fL:',fL)


fx: -60*L + 48.0*x**(-0.4)*y**0.4
fy: -100*L + 32.0*x**0.6*y**(-0.6)
fL: -60*x - 100*y + 500000


In [47]:
# critical point 1 
(48*(x**-.4)*(y**.4))/60

4*x**(-0.4)*y**0.4/5

In [48]:
# critical point 2
(32*(x**.6)*(y**-.6))/100

8*x**0.6*y**(-0.6)/25

In [51]:
60*(5/2) + 100

250.0

In [52]:
500000/250

2000.0

### Functions with more than 1 input

In [2]:
x = Symbol('x')
y = Symbol('y')

In [3]:
function_u = 6*x-9*y+2
function = lambdify([x,y],function_u,'numpy')

In [4]:
function(0,6)

-52

#### Problem 3

In [5]:
w = Symbol('w')
r = Symbol('r')
a = Symbol('a')

In [6]:
function_u = 41 - 1.73*w-1.26*r-1.32*a
function = lambdify([w,r,a],function_u,'numpy')

In [7]:
function(3,15,0)

16.910000000000004

### Problem 6

In [8]:
s = Symbol('s')
n = Symbol('n')
a = Symbol('a')

In [9]:
function_u = 0.076*a + (4*(s*n)**(1/2))
function = lambdify([s,n,a],function_u,'numpy')
function_u

0.076*a + 4*(n*s)**0.5

In [10]:
function(8,6,470)

63.432812921102034

In [11]:
function(2,1,340)

31.49685424949238

f_n = partial derivative with respect to n

In [16]:
partial_deriv_u = diff(function_u, a)
partial_deriv = lambdify([n,s],partial_deriv_u,'numpy')
partial_deriv_u

0.0760000000000000

In [17]:
partial_deriv(1,2)

0.076

In [20]:
2*(2**(1/2))

2.8284271247461903

### Problem 7

In [26]:
coefficients = np.matrix([[6, 1],
                          [1, 2]])
constants    = np.array([-33, 0])
intersection = np.linalg.solve(coefficients1,constants1)
intersection

array([-6.,  3.])

In [79]:
coefficients = np.matrix([[6, -4,-1],
                          [-4, 2, -1],
                          [1,1, 0]])
constants    = np.array([0, 0,8])
intersection = np.linalg.solve(coefficients,constants)
intersection

array([ 3.,  5., -2.])

### Problem 9 - System of nonlinear equations

In [73]:
def myFunction(z):
    x = z[0]
    y = z[1]
    
    f = [0,0]
    f[0] = 4*x**3 -32*y
    f[1] = -32*x - 64*y**3
    
    return f

In [74]:
zGuess = np.array([80,80])

In [75]:
z = fsolve(myFunction,zGuess)

In [76]:
print(z)

[0. 0.]


In [86]:
r = 1.5
h = 15
dr = .09
dh = .18

In [87]:
2*math.pi*r*h*dr+math.pi*r**2*dh

13.995795271742526

In [95]:
l = 4
r = 2.5
p = 0.08

In [96]:
v_t_b = math.pi*r**2*p

In [97]:
v_s = 2*math.pi*r*l*p

In [98]:
2*v_t_b+v_s

8.168140899333462