In [104]:
import numpy as np
from numpy.linalg import linalg, inv

Solve For Variables

In [5]:
#Question 1

#If 30 lb of rice and 20 lb of potatoes cost $21.20, and 20 lb of rice and 12 lb of potatoes 
#cost $13.52, how much will 10 lb of rice and 50 lb of potatoes cost?

coefficients = np.array([[30,20],[20,12]])
constants = np.array([21.2,13.52])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')

solution = 10*variables[0] + 50*variables[1]

print(f'The total cost is: {solution}.')

The variables are: [0.4  0.46].
The total cost is: 26.999999999999986.


In [6]:
# Question 2

#A person has $42,000 invested in stock A and stock B. Stock A currently sells 
#for $20 a share and stock B sells for $80 a share. If stock B triples in value 
#and stock A goes up 50%, his stock will be worth $111,000. How many shares of 
#each stock does he own?

coefficients = np.array([[20,80],[30,240]])
constants = np.array([42000,111000])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')

#solution = 10*variables[0] + 50*variables[1]

#print(f'The total cost is: {solution}.')

The variables are: [500. 400.].


In [7]:
# Question 4
coefficients = np.array([[1,1,-1],[3,-1,1],[1,-4,2]])
constants = np.array([3,-3,-38])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')


#solution = 10*variables[0] + 50*variables[1]
#print(f'The total cost is: {solution}.')

The variables are: [1.18423789e-15 1.60000000e+01 1.30000000e+01].


In [8]:
# Question 5

# A rental truck company plans to spend $8 million on 280 new vehicles. Each 
# commercial van will cost $25,000, each small truck $30,000, and each large 
# truck $40,000. Past experience shows that they need twice as many vans as 
# small trucks. How many of each type of vehicle can they buy?

coefficients = np.array([[1,1,1],[25000,30000,40000],[1,-2,0]])
constants = np.array([280,8000000,0])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')

The variables are: [160.  80.  40.].


In [9]:
# Question 6

# In a certain season, a baseball player had a total of 146 hits. He hit two 
# fewer triples than home runs, and he also hit three times as many doubles as 
# home runs. Additionally, he hit 41 times as many singles as triples. 
# Find the number of singles, doubles, triples, and home runs hit by the
# player during the season.

coefficients = np.array([[1,1,1,1],
                         [1,-1,0,0],
                         [-3,0,1,0],
                         [0,-41,0,1]])
constants = np.array([146,2,0,0])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')

The variables are: [  5.   3.  15. 123.].


In [34]:
# Question 7

# There are three convenience stores in Gambier. This week, Store I sold 84 
# loaves of bread, 44 quarts of milk, 16 jars of peanut butter, and 112 
# pounds of cold cuts. Store II sold 108 loaves of bread, 72 quarts of milk, 
# 18 jars of peanut butter, and 150 pounds of cold cuts. Store III sold 60 bread, 
# 30 quarts of milk, no peanut butter, and 70 pounds of cold cuts. 

store1 = [84,44,16,112]
store2 = [108,72,18,150]
store3 = [60,30,0,70]

matrix = np.array([store1,store2,store3])
print('First week sales matrix:') 
print(matrix)


# During the following week, store 1 increased 25% sales, store2 1/3, store 3 10%
sale_change = [[1.25],
               [4/3],
               [1.1]]

new_week_sales_matrix = matrix * sale_change
print('New week sales matrix:') 
print(new_week_sales_matrix)

total_sales = matrix + new_week_sales_matrix
print('Total sales matrix:') 
print(total_sales)

First week sales matrix:
[[ 84  44  16 112]
 [108  72  18 150]
 [ 60  30   0  70]]
New week sales matrix:
[[105.  55.  20. 140.]
 [144.  96.  24. 200.]
 [ 66.  33.   0.  77.]]
Total sales matrix:
[[189.  99.  36. 252.]
 [252. 168.  42. 350.]
 [126.  63.   0. 147.]]


In [77]:
# Question 8
#                          Country B  |    Country C
#                         Aimp | Aexp |   Aimp| Aexp   
food_and_live_animals = ([20.8 ,17.4]   ,[10.2,12.3])
beverages_and_tobacco = ([1.4  ,0.8]    ,[0.5 ,3.1])
crude_minerals        = ([7.3  ,14.3]   ,[6.8 ,2.6])
mineral_fuels         = ([17.6 ,101.8]  ,[24.7,39.1])
chemicals             = ([34.9 ,25.4]   ,[25.3,5.7])
manufactured_goods    = ([36.8 ,39.5]   ,[28.1,19.5])
machinery             = ([126.9,93.9]   ,[91.6,154.4])


countryB = np.array([food_and_live_animals[0],
                     beverages_and_tobacco[0],
                     crude_minerals[0],
                     mineral_fuels[0],
                     chemicals[0],
                     manufactured_goods[0],
                     machinery[0]])
print('Country B Matrix:\n {}'.format(countryB))

countryC = np.array([food_and_live_animals[1],
                     beverages_and_tobacco[1],
                     crude_minerals[1],
                     mineral_fuels[1],
                     chemicals[1],
                     manufactured_goods[1],
                     machinery[1]])
print('\nCountry C Matrix:\n {}'.format(countryC))

total_trade = countryB + countryC
print('\nTotal trade Matrix:\n {}'.format(total_trade))

difference_in_trade = countryB - countryC
print('\nTotal trade Matrix:\n {}'.format(difference_in_trade))

Country B Matrix:
 [[ 20.8  17.4]
 [  1.4   0.8]
 [  7.3  14.3]
 [ 17.6 101.8]
 [ 34.9  25.4]
 [ 36.8  39.5]
 [126.9  93.9]]

Country C Matrix:
 [[ 10.2  12.3]
 [  0.5   3.1]
 [  6.8   2.6]
 [ 24.7  39.1]
 [ 25.3   5.7]
 [ 28.1  19.5]
 [ 91.6 154.4]]

Total trade Matrix:
 [[ 31.   29.7]
 [  1.9   3.9]
 [ 14.1  16.9]
 [ 42.3 140.9]
 [ 60.2  31.1]
 [ 64.9  59. ]
 [218.5 248.3]]

Total trade Matrix:
 [[ 10.6   5.1]
 [  0.9  -2.3]
 [  0.5  11.7]
 [ -7.1  62.7]
 [  9.6  19.7]
 [  8.7  20. ]
 [ 35.3 -60.5]]


In [79]:
# Question 9 - Life expectancy 
#        Group A    |  Group B
#       Male|Female | Male|Female  
y1970 = ([60.0,67.4],[68.0,75.9])
y1980 = ([62.8,71.8],[70.2,78.8])
y1990 = ([64.1,73.6],[72.7,79.4])
y2000 = ([68.7,75.1],[73.5,79.7])
y2010 = ([71.8,78.0],[76.7,81.4])

groupA = np.array([y1970[0],
                   y1980[0],
                   y1990[0],
                   y2000[0],
                   y2010[0]])
print('Group A life expentancy Matrix:\n {}'.format(groupA))

groupB = np.array([y1970[1],
                   y1980[1],
                   y1990[1],
                   y2000[1],
                   y2010[1]])
print('\nGroup B life expentancy Matrix:\n {}'.format(groupB))


difference_in_life_expectancy = groupA - groupB
print('\nDifference in life expectancy Matrix:\n {}'.format(difference_in_life_expectancy))

Group A life expentancy Matrix:
 [[60.  67.4]
 [62.8 71.8]
 [64.1 73.6]
 [68.7 75.1]
 [71.8 78. ]]

Group B life expentancy Matrix:
 [[68.  75.9]
 [70.2 78.8]
 [72.7 79.4]
 [73.5 79.7]
 [76.7 81.4]]

Difference in life expectancy Matrix:
 [[-8.  -8.5]
 [-7.4 -7. ]
 [-8.6 -5.8]
 [-4.8 -4.6]
 [-4.9 -3.4]]


In [87]:
# Question 10

A = np.array([[-2,5],
              [ 1,3]])

B = np.array([[-2,1],
              [ 3,9]])

incorrect_AB = A*B
print('The incorrect matrix is: \n{}'.format(incorrect_AB))

correct_AB   = np.dot(A,B) 
print('\nThe correct matrix is: \n{}'.format(correct_AB))

correct_BA   = np.dot(B,A) 
print('\nThe correct matrix is: \n{}'.format(correct_BA))

The incorrect matrix is: 
[[ 4  5]
 [ 3 27]]

The correct matrix is: 
[[19 43]
 [ 7 28]]

The correct matrix is: 
[[ 5 -7]
 [ 3 42]]


In [90]:
# Question 11

storeA = [90,60,100]
storeB = [60,50,150]

total_store = np.array([storeA, storeB])
print('Total store price matrix: \n {}'.format(total_store))

shoeStoreSales   = [1/2,1/5]
sandalStoreSales = [1/4,1/5]
bootStoreSales   = [1/4,3/5]

store_sale = np.array([shoeStoreSales, sandalStoreSales, bootStoreSales])
print('Sale by store matrix: \n {}'.format(store_sale))

store_to_sales = np.dot(total_store,store_sale) 
print('\nStore to sales ratio: \n{}'.format(store_to_sales))

Total store price matrix: 
 [[ 90  60 100]
 [ 60  50 150]]
Sale by store matrix: 
 [[0.5  0.2 ]
 [0.25 0.2 ]
 [0.25 0.6 ]]

Store to sales ratio: 
[[ 85.  90.]
 [ 80. 112.]]


In [97]:
# Question 12: Average Vehicle Sales 
#       Jan     feb     march
#           cars/trucks 
new  = ([15,12],[14,13],[25,20])
used = ([23,18],[37,26],[27,40])

jan  = np.array([new[0],
                used[0]])
feb  = np.array([new[1],
                used[1]])
mar  = np.array([new[2],
                used[2]])

first_quarter = jan + feb + mar

print(first_quarter)

q_avg_conversion = np.array([[1/3,1/3],
                             [1/3,1/3]])

print(q_avg_conversion)

first_quarter_average = first_quarter * q_avg_conversion
print(first_quarter_average)

[[54 45]
 [87 84]]
[[0.33333333 0.33333333]
 [0.33333333 0.33333333]]
[[18. 15.]
 [29. 28.]]


In [107]:
# Question 13: Find the Inverse 

matrix = np.matrix([[1,-1,5],
                    [0, 1,7],
                    [2,-3,2]])
print('Matrix: \n {}'.format(matrix))

inverse_matrix = inv(matrix)
print('\nInverse matrix: \n {}'.format(inverse_matrix))



Matrix: 
 [[ 1 -1  5]
 [ 0  1  7]
 [ 2 -3  2]]

Inverse matrix: 
 [[-23.  13.  12.]
 [-14.   8.   7.]
 [  2.  -1.  -1.]]


In [109]:
# Question 14
# type   1 2 3
flour = [1,2,4]
sugar = [2,1,2]
eggs  = [2,1,3]

ingrediant_matrix = np.matrix([flour, sugar, eggs])
print('Ingrediant Matrix: \n{}'.format(ingrediant_matrix))

ingrediant_matrix = np.matrix([flour, sugar, eggs])
print('Ingrediant Matrix: \n{}'.format(ingrediant_matrix))

Ingrediant Matrix: 
[[1 2 4]
 [2 1 2]
 [2 1 3]]


In [110]:
# Question 14

coefficients = np.array([[2,6,4],[2,1,2],[2,1,3]])
constants = np.array([106,45,58])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')

The variables are: [ 6.  7. 13.].


In [1]:
# Question 14

coefficients = np.array([[2,6,4],[2,1,2],[2,1,3]])
constants = np.array([106,45,58])
variables = np.linalg.solve(coefficients,constants)

print(f'The variables are: {variables}.')

NameError: name 'np' is not defined

In [2]:
# Question 15: vitamin tablets 

tablet_a = [13,12]
tablet_b = [18,15]
tablet_c = [23,35]
tablet_matrix = np.matrix([tablet_a,
                           tablet_b,
                           tablet_c])
print('Tablet Matrix: \n{}'.format(tablet_matrix))

mix1 = [4300,5225]
mix2 = [2985,3440]
mix3 = [4530,4830]
mix_matrix = np.matrix([mix1,
                        mix2,
                        mix3])
print('\nMix Matrix: \n{}'.format(mix_matrix))

total_tablets = np.matrix([[225],
                           [170],
                           [260]])
print('\nTotal tablets Matrix: \n{}'.format(total_tablets))



NameError: name 'np' is not defined

In [128]:
# Question 15: vitamin tablets 

matrix = np.matrix([[1,1,1],
                        [13,18,23],
                        [12,15,35]])
print('\nMix Matrix: \n{}'.format(mix_matrix))

inverse_matrix = inv(matrix)
print('\nInverse matrix: \n {}'.format(inverse_matrix))

mix_matrix1 = np.matrix([[225],[4300],[5225]])
print('\nMix Matrix 1: \n {}'.format(mix_matrix1))
mix1_solution = np.dot(inverse_matrix,mix_matrix1) 
print('\nTable mix for scenario A is: \n{}'.format(mix1_solution))

mix_matrix2 = np.matrix([[170],[2985],[3440]])
print('\nMix Matrix 2: \n {}'.format(mix_matrix2))
mix2_solution = np.dot(inverse_matrix,mix_matrix2) 
print('\nTable mix for scenario B is: \n{}'.format(mix2_solution))

mix_matrix3 = np.matrix([[260],[4530],[4830]])
print('\nMix Matrix 2: \n {}'.format(mix_matrix3))
mix3_solution = np.dot(inverse_matrix,mix_matrix3) 
print('\nTable mix for scenario B is: \n{}'.format(mix3_solution))


Mix Matrix: 
[[ 1  1  1]
 [13 18 23]
 [12 15 35]]

Inverse matrix: 
 [[ 3.35294118 -0.23529412  0.05882353]
 [-2.10588235  0.27058824 -0.11764706]
 [-0.24705882 -0.03529412  0.05882353]]

Mix Matrix 1: 
 [[ 225]
 [4300]
 [5225]]

Table mix for scenario A is: 
[[ 50.]
 [ 75.]
 [100.]]

Mix Matrix 2: 
 [[ 170]
 [2985]
 [3440]]

Table mix for scenario B is: 
[[70.]
 [45.]
 [55.]]

Mix Matrix 2: 
 [[ 260]
 [4530]
 [4830]]

Table mix for scenario B is: 
[[ 90.]
 [110.]
 [ 60.]]
