In [25]:
import matplotlib.pyplot 
from matplotlib.pyplot import *
import numpy as np
from scipy.optimize import linprog
import math

# settings
np.set_printoptions(suppress=True, linewidth=100)

from pulp import LpVariable, LpProblem, LpMaximize, LpStatus, value, LpMinimize

In [31]:
def print_rows(a,b,c,d):
    temp = np.concatenate((a,b,c,d), axis =0)
    print(temp)

# Maximize
<br>z = 3*x1 + 2*x2 + x3
<br>Contraints: 
<br>2 * x1 + x2 + x3 <= 150
<br>x1 + 2 * x2 + 8 * x3 <= 200
<br>2 * x1 + 3 * x2 + x3 <= 320
<br>With: 
<br>x1 -- x3 nonnegative 

In [7]:
# Long form


# Create Simplex Tableau Matrix 
column_headings = '   x1  x2  x3  s1  s2  s3   z'
R1 = np.array([[2 ,1 ,1 ,1 ,0 ,0 ,0 ,150]])
R2 = np.array([[1 ,2 ,8 ,0 ,1 ,0 ,0 ,200]])
R3 = np.array([[2 ,3 ,1 ,0 ,0 ,1 ,0 ,320]])
# indicators are negative to fulfill: -x1-x2-x3+z=0
R4 = np.array([[-3 ,-2 ,-1 ,0 ,0 ,0 ,1 ,  0]]) 
print("Simplex Tableau:")
print(column_headings)
print_rows(R1,R2,R3,R4)


# Pivot
# column 1 because most negative indicator
# row 1 because 150/2 yields smallest nonnegative real integer in column
R2 = -R1 + 2*R2
R3 = -R1 + R3
R4 = 3*R1 +2*R4
print("\nSimplex Tableau - Pivotted:")
print(column_headings)
print_rows(R1,R2,R3,R4)


# Simplify Pivot
R1 = 0.5*R1
R2 = 0.5*R2
R4 = 0.5*R4
print("\nFinal Simplex Tableau:")
column_headings = '    x1    x2    x3    s1    s2    s3    z'
print(column_headings)
print_rows(R1,R2,R3,R4)

Simplex Tableau:
   x1  x2  x3  s1  s2  s3   z
[[  2   1   1   1   0   0   0 150]
 [  1   2   8   0   1   0   0 200]
 [  2   3   1   0   0   1   0 320]
 [ -3  -2  -1   0   0   0   1   0]]

Simplex Tableau - Pivotted:
   x1  x2  x3  s1  s2  s3   z
[[  2   1   1   1   0   0   0 150]
 [  0   3  15  -1   2   0   0 250]
 [  0   2   0  -1   0   1   0 170]
 [  0  -1   1   3   0   0   2 450]]

Final Simplex Tableau:
    x1    x2    x3    s1    s2    s3    z
[[  1.    0.5   0.5   0.5   0.    0.    0.   75. ]
 [  0.    1.5   7.5  -0.5   1.    0.    0.  125. ]
 [  0.    2.    0.   -1.    0.    1.    0.  170. ]
 [  0.   -0.5   0.5   1.5   0.    0.    1.  225. ]]


# Maximize
<br> Maximize: 
<br> z = 5x1 + x2
<br> Subject To: 
<br> 4x1 + 2x2 <= 8
<br>  x1 + 2x2 <= 4
<br> With x1 & x2 >= 0

In [29]:
# Create Simplex Tableau Matrix 
column_headings = '   x1 x2 s1 s2 z'
R1 = np.array([[4 ,2 ,1 ,0 ,0 ,8]])
R2 = np.array([[1 ,2 ,0 ,1 ,0 ,4]])
# indicators are negative to fulfill: -x1-x2-x3+z=0
R3 = np.array([[-5 ,-1 ,0 ,0 ,1 ,  0]]) 
print("Simplex Tableau:")
print(column_headings)
print_rows(R1,R2,R3)

# Pivot
# column 1 because most negative indicator
# row 1 because 8/4 yields smallest nonnegative real integer in column
R2 = R2 - (1/4)*R1
R3 = R3 + (5/4)*R1
print("\nSimplex Tableau - Pivotted:")
print(column_headings)
print_rows(R1,R2,R3)

Simplex Tableau:
   x1 x2 s1 s2 z
[[ 4  2  1  0  0  8]
 [ 1  2  0  1  0  4]
 [-5 -1  0  0  1  0]]

Simplex Tableau - Pivotted:
   x1 x2 s1 s2 z
[[ 4.    2.    1.    0.    0.    8.  ]
 [ 0.    1.5  -0.25  1.    0.    2.  ]
 [ 0.    1.5   1.25  0.    1.   10.  ]]


# Minimization

In [21]:
# Create Simplex Tableau Matrix 
R1 = np.array([[  2.5,   5,   1, 0, 0, 0,  6]])
R2 = np.array([[  4.5,   3,   0, 1, 0, 0,  9]])
R3 = np.array([[    5,  10,   0, 0, 1, 0, 10]])
R4 = np.array([[  -60, -66,   0, 0, 0, 1,  0]])
print("Simplex Tableau:")
print_rows(R1,R2,R3,R4)

# Pivot column 2 Column row 3
R1 = R1 - .5*R3
R2 = R2 - (3/10)*R3
R4 = R4 + (66/10)*R3

print("\nSimplex Tableau - Pivotted:")
print_rows(R1,R2,R3,R4)

# Pivot column 1 row 3
R2 = (27/3)*R2 + R4
R4 = R4 + (27/5)*R3
print("\nSimplex Tableau - Pivotted - 2:")
print_rows(R1,R2,R3,R4)

print("\n 12 units of s2 for 120 total")

Simplex Tableau:
[[  2.5   5.    1.    0.    0.    0.    6. ]
 [  4.5   3.    0.    1.    0.    0.    9. ]
 [  5.   10.    0.    0.    1.    0.   10. ]
 [-60.  -66.    0.    0.    0.    1.    0. ]]

Simplex Tableau - Pivotted:
[[  0.    0.    1.    0.   -0.5   0.    1. ]
 [  3.    0.    0.    1.   -0.3   0.    6. ]
 [  5.   10.    0.    0.    1.    0.   10. ]
 [-27.    0.    0.    0.    6.6   1.   66. ]]

Simplex Tableau - Pivotted - 2:
[[  0.    0.    1.    0.   -0.5   0.    1. ]
 [  0.    0.    0.    9.    3.9   1.  120. ]
 [  5.   10.    0.    0.    1.    0.   10. ]
 [  0.   54.    0.    0.   12.    1.  120. ]]

 12 units of s2 for 120 total


In [22]:
# Slack variables and interpretation
def print_rows(a,b,c,d):
    temp = np.concatenate((a,b,c,d), axis =0)
    print(temp)

# Create Simplex Tableau Matrix 
R1 = np.array([[  2.5,   5,   1, 0, 0, 0,  6]])
R2 = np.array([[  4.5,   3,   0, 1, 0, 0,  9]])
R3 = np.array([[    5,  10,   0, 0, 1, 0, 10]])
R4 = np.array([[  -60, -66,   0, 0, 0, 1,  0]])
print("Simplex Tableau:")
print_rows(R1,R2,R3,R4)

# Pivot column 2 Column row 3
R1 = R1 - .5*R3
R2 = R2 - (3/10)*R3
R4 = R4 + (66/10)*R3

print("\nSimplex Tableau - Pivotted:")
print_rows(R1,R2,R3,R4)

# Pivot column 1 row 2
R3 = R3 - (5/3)*R2
R4 = R4 + (27/3)*R2
print("\nx1,x2,s1,s2,s3,z")
print("Simplex Tableau - Pivotted - 2:")
print_rows(R1,R2,R3,R4)

print("\n9 units of s2, 3.9 units of s3 as 120 total")

Simplex Tableau:
[[  2.5   5.    1.    0.    0.    0.    6. ]
 [  4.5   3.    0.    1.    0.    0.    9. ]
 [  5.   10.    0.    0.    1.    0.   10. ]
 [-60.  -66.    0.    0.    0.    1.    0. ]]

Simplex Tableau - Pivotted:
[[  0.    0.    1.    0.   -0.5   0.    1. ]
 [  3.    0.    0.    1.   -0.3   0.    6. ]
 [  5.   10.    0.    0.    1.    0.   10. ]
 [-27.    0.    0.    0.    6.6   1.   66. ]]

x1,x2,s1,s2,s3,z
Simplex Tableau - Pivotted - 2:
[[  0.           0.           1.           0.          -0.5          0.           1.        ]
 [  3.           0.           0.           1.          -0.3          0.           6.        ]
 [  0.          10.           0.          -1.66666667   1.5          0.           0.        ]
 [  0.           0.           0.           9.           3.9          1.         120.        ]]

9 units of s2, 3.9 units of s3 as 120 total


# Pivotting Slack Variables

In [32]:
# Create Simplex Tableau Matrix 
R1 = np.array([[2 ,2 ,1 ,1 ,0, 0 ,0 ,11]])
R2 = np.array([[1 ,2 ,3 ,0 ,1, 0 ,0 ,45]])
R3 = np.array([[3 ,1 ,1 ,0 ,0, 1 ,0 ,18]])
# indicators are negative to fulfill: -x1-x2-x3+z=0
R4 = np.array([[-2 ,-1 ,-3 ,0 ,0, 0 ,1 ,0]]) 
print("Simplex Tableau:")
print(column_headings)
print_rows(R1,R2,R3,R4)

# Pivot column 3 row 1
R2 -= 3*R1
R3 -=   R1
R4 += 3*R1
print("\nSimplex Tableau - Pivotted:")
print(column_headings)
print_rows(R1,R2,R3,R4)

Simplex Tableau:
   x1 x2 s1 s2 z
[[ 2  2  1  1  0  0  0 11]
 [ 1  2  3  0  1  0  0 45]
 [ 3  1  1  0  0  1  0 18]
 [-2 -1 -3  0  0  0  1  0]]

Simplex Tableau - Pivotted:
   x1 x2 s1 s2 z
[[ 2  2  1  1  0  0  0 11]
 [-5 -4  0 -3  1  0  0 12]
 [ 1 -1  0 -1  0  1  0  7]
 [ 4  5  0  3  0  0  1 33]]
